title: Lê Việt Hùng
logo: /avatar.png
description: I'm a senior student at FPT University with 5 months of internship experience at FPT Software. During this time, I worked on both backend and frontend development with C# and ReactJS. I gained exposure to Agile methodologies and microservices architecture.
show_downloads: true
theme: jekyll-theme-minimal
